server:
  port: ${PORT:8080}
  address: "::"
  forward-headers-strategy: native
  ssl:
    enabled: false
  servlet:
    session:
      cookie:
        domain: 'embrave.app'

spring:
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: ${AUTH0_CLIENT_ID}
            client-secret: ${AUTH0_CLIENT_SECRET}
            scope:
              - openid
              - profile
              - email
        provider:
          auth0:
            # trailing slash is important!
            issuer-uri: https://embrave.eu.auth0.com/

  cloud:
    gateway:
      httpclient:
        ssl:
          use-insecure-trust-manager: true
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins: ${FRONTEND_URL}
            #allowedOrigins: http://app-frontend:3000
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - OPTIONS
            allowCredentials: true
      routes:

        - id: backend
          uri: ${BACKEND_URL}
          #uri: http://app-backend:8081
          predicates:
            - Path=/api/**
          filters:
            - StripPrefix=1


auth0:
  audience: https://embrave.eu.auth0.com/api/v2/

logoutReturnUrl: ${FRONTEND_URL}

debug: true
logging:
  level:
    root: debug
