spring:
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: ${AUTH0_CLIENT_ID}
            client-secret: ${AUTH0_CLIENT_SECRET}
            scope:
              - openid
              - profile
              - email
        provider:
          auth0:
            # trailing slash is important!
            issuer-uri: https://embrave.eu.auth0.com/

  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins: http://localhost:3000
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
            allowCredentials: true
      routes:
        - id: backend
          uri: http://localhost:8081
          predicates:
            - Path=/
          filters:
            - TokenRelay
            - RemoveRequestHeader=Cookie

auth0:
  audience: https://embrave.app

debug: true
logging:
  level:
    org:
      springframework:
        security: DEBUG
        gateway: DEBUG
