spring:
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: fill
            client-secret: fill
            scope:
              - openid
              - profile
              - email
        provider:
          auth0:
            # trailing slash is important!
            issuer-uri: https://embrave.eu.auth0.com/

  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins: http://app-frontend:3000
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
            allowCredentials: true
      routes:

        - id: stripe
          uri: http://localhost:3000
          #uri: http://app-frontend:3000
          predicates:
            - Path=/api/checkout_sessions

        - id: backend
          uri: http://app-backend:8081
          predicates:
            - Path=/api/**
          filters:
            - StripPrefix=1

        - id: websocket
          uri: ws://app-frontend:3000/
          predicates:
            - Path=/websocket/**

        - id: frontend
          uri: http://app-frontend:3000
          predicates:
            - Path=/**

auth0:
  audience: https://embrave.eu.auth0.com/api/v2/

logoutReturnUrl: http://localhost:8080/

debug: true
logging:
  level:
    root: debug
