version: '4'

services:
  minio:
    image: quay.io/minio/minio:latest
    command: server /data --console-address ":9090"
    expose:
      - '9000:9000'
      - '9090:9090'
    ports:
      - '9000:9000'
      - '9090:9090'
    volumes:
      - ~/minio/data:/data
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: adminadmin