server.port: 8081
spring:
  servlet:
    multipart:
      max-file-size: 5MB
  mvc:
    log-request-details: true
  main:
    allow-bean-definition-overriding: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://embrave.eu.auth0.com/
  datasource :
    url: jdbc:mysql://localhost:3306/Embrave
    #url: jdbc:mysql://app-db:3306/Embrave
    username: user
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update

debug: true
logging:
  level:
    root: debug

server:
  error:
    include-message: always
