server:
  port: ${PORT:8081}
  address: "::"
  error:
    include-message: always
  ssl:
    enabled: false

spring:
  servlet:
    multipart:
      max-file-size: 5MB
  mvc:
    log-request-details: true
  main:
    allow-bean-definition-overriding: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://embrave.eu.auth0.com/
  datasource :
    url: ${DATASOURCE_URL}
    #url: jdbc:mysql://app-db:3306/Embrave
    username: ${DATASOURCE_USER}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update

minio:
  host: ${MINIO_HOST}
  port: ${MINIO_PORT}
  user: ${MINIO_USER}
  password: ${MINIO_PASSWORD}

gateway:
  url: ${GATEWAY_URL}

debug: true
logging:
  level:
    root: debug
