server.port: 8081
spring:
  mvc:
    log-request-details: true
  main:
    allow-bean-definition-overriding: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://embrave.eu.auth0.com/
  datasource :
    url: jdbc:mysql://localhost:3306/embrave
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update

auth0:
  audience: https://embrave.eu.auth0.com/api/v2/

debug: true
logging:
  level:
    root: debug
